[package]
name = "rta-derive"
edition = "2024"
version = "0.1.0"
readme = "README.md"
license = "MIT OR Apache-2.0"
description = "Macro implementation for Ṛta"
repository = "https://github.com/frozen-lab/rta"
keywords = ["rta", "database", "persistence", "storage"]
categories = ["caching", "configuration", "database-implementations", "no-std", "no-std::no-alloc"]

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"

[lib]
proc-macro = true
