[package]
edition = "2024"
name = "rta"
version = "0.0.2"
description = "Ṛta (ऋत) is a minimal metadata store for durable system state"
readme = "../README.md"
keywords = [
    "rta",
    "database",
    "persistence",
    "storage",
]
categories = [
    "caching",
    "database-implementations",
]
license = "MIT OR Apache-2.0"
repository = "https://github.com/frozen-lab/rta"

[lib]
name = "rta"
path = "src/lib.rs"

[dependencies.frozen-core]
version = "0.0.18"
default-features = false
features = [
    "crc32",
    "fmmap",
]

[dependencies.rta-derive]
version = "0.3.0"

[dev-dependencies.tempfile]
version = "3.20.0"
